### ISSUE TITLE
Failed to execute "kuberam-expath-plugin" on Windows platform

### ISSUE THREAD

**Issue by dovikos** [claudius108/kuberam-expath-plugin#1]
Hello, 
I report here an issue detected in the [xquery-versioning-module project](https://github.com/eXist-db/xquery-versioning-module/issues/4).

Executing plugin `kuberam-expath-plugin` throws an `java.io.FileNotFoundException`.
It seems that the bug appears on Windows platform.
My operating system is Windows 7.

Here is the full stacktrace (I put in bold relevant informations to me):
<pre>[INFO] --- kuberam-expath-plugin:0.4.8:make-xar (create-xar) @ xquery-versioning-module ---
[INFO] descriptorsDirectoryPath: C:\Users\[some path]\xquery-versioning-module\target\expath-descriptors-7a87d469-cd5d-4b21-ae88-ca8f9de89d0a
mavenResourcesExecution: org.apache.maven.shared.filtering.MavenResourcesExecution@4a9860
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource to C:\Users\[some path]\xquery-versioning-module\target\make-xar-tmp
[INFO] Resolved artifact: org.exist-db.xquery.extensions:xquery-versioning-module:jar:1.1.2
<strong>java.io.FileNotFoundException: \\C\Users\[some path]\xquery-versioning-module\target\xquery-versioning-module-1.1.2.jar (Le chemin réseau n'a pas été trouvé)</strong>
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:94)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
	at java.net.JarURLConnection.getManifest(JarURLConnection.java:231)
	at java.net.JarURLConnection.getMainAttributes(JarURLConnection.java:283)
	at ro.kuberam.maven.plugins.expath.mojos.MakeXarMojo.getMainClass(MakeXarMojo.java:273)
	at ro.kuberam.maven.plugins.expath.mojos.MakeXarMojo.execute(MakeXarMojo.java:177)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.027 s
[INFO] Finished at: 2017-03-23T08:54:03+01:00
[INFO] Final Memory: 21M/231M
[INFO] ------------------------------------------------------------------------
[ERROR] <strong>Failed to execute goal ro.kuberam.maven.plugins:kuberam-expath-plugin:0.4.8:make-xar (create-xar) on project xquery-versioning-module</strong>: Execution create-xar of goal ro.kuberam.maven.plugins:kuberam-expath-plugin:0.4.8:make-xar failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal ro.kuberam.maven.plugins:kuberam-expath-plugin:0.4.8:make-xar (create-xar) on project xquery-versioning-module: Execution create-xar of goal ro.kuberam.maven.plugins:kuberam-expath-plugin:0.4.8:make-xar failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution create-xar of goal ro.kuberam.maven.plugins:kuberam-expath-plugin:0.4.8:make-xar failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at ro.kuberam.maven.plugins.expath.mojos.MakeXarMojo.getMainClass(MakeXarMojo.java:278)
	at ro.kuberam.maven.plugins.expath.mojos.MakeXarMojo.execute(MakeXarMojo.java:177)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more</pre>

Dovikos

**Comment by claudius108** [comment]
I was not able to reproduce this in ubuntu. What maven version do you have?

**Comment by dovikos** [comment]
I'm using **Apache Maven 3.3.9**, but please note that I'm working on a **Windows** platform (Windows 7).

**Comment by claudius108** [comment]
I was not able to reproduce this in ubuntu. What maven version do you have?

**Comment by claudius108** [comment]
What if you put the plugin kuberam-expath-plugin to be the last one in build/plugins?

**Comment by dovikos** [comment]
The error is still occurring, event if the plugin is the last one in build/plugins.
I'm working on a **Windows** platform (Windows 7).

**Comment by adamretter** [comment]
@claudius108 This issue only occurs on the Windows platform. There is another report of it here - https://github.com/eXist-db/expath-file-module/issues/5

**Comment by hra-team** [comment]
I did not manage to reproduce the issue on windows 7, as I got other error related to the pom itself. i will try more.
