### ISSUE TITLE
Plugin issue on windows7: JAR not picked up into XAR

### ISSUE THREAD

**Issue by dizzzz** [claudius108/kuberam-expath-plugin#13]
It seems to be impossible to build with the kuberam-expath-plugin under Windows (7, 64 bit); The JAR file is generated, but during XAR generation the JAR is not found;

JAR creation:
```
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ messaging-replication ---
[INFO] Building jar: C:\Dev\GitHub\messaging-replication\target\messaging-replication-0.30.4.jar
```

XAR issue
```
[INFO] artifactFile: C:\Dev\GitHub\messaging-replication\target\messaging-replication-0.30.4.jar
java.nio.file.FileSystemException: \\C\Dev\GitHub\messaging-replication\target\messaging-replication-0.30.4.jar: The network path was not found.
```

My project is [here](https://github.com/eXist-db/messaging-replication/tree/feature/archetype). This is the whole log:

```
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ messaging-replication ---
[INFO] Building jar: C:\Dev\GitHub\messaging-replication\target\messaging-replication-0.30.4.jar
[INFO] 
[INFO] --- kuberam-expath-plugin:0.5.4:make-xar (create-xar) @ messaging-replication ---
outputDirectoryPath = C:\Dev\GitHub\messaging-replication\target
[INFO] descriptorsDirectoryPath: C:\Dev\GitHub\messaging-replication\target\expath-descriptors
mavenResourcesExecution: org.apache.maven.shared.filtering.MavenResourcesExecution@6364e814
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource to C:\Dev\GitHub\messaging-replication\target\make-xar-tmp
[INFO] Resolved artifact: org.exist:messaging-replication:jar:0.30.4
[INFO] artifactFile: C:\Dev\GitHub\messaging-replication\target\messaging-replication-0.30.4.jar
java.nio.file.FileSystemException: \\C\Dev\GitHub\messaging-replication\target\messaging-replication-0.30.4.jar: The network path was not found.

	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:194)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1755)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:951)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:216)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:148)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:324)
	at java.base/sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:103)
	at java.base/sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:72)
	at java.base/sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:94)
	at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:125)
	at java.base/sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:92)
	at java.base/java.net.JarURLConnection.getManifest(JarURLConnection.java:239)
	at java.base/java.net.JarURLConnection.getMainAttributes(JarURLConnection.java:291)
	at ro.kuberam.maven.plugins.expath.mojos.MakeXarMojo.getMainClass(MakeXarMojo.java:404)
	at ro.kuberam.maven.plugins.expath.mojos.MakeXarMojo.execute(MakeXarMojo.java:273)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.123 s
[INFO] Finished at: 2018-02-12T13:00:07+01:00
[INFO] Final Memory: 41M/2024M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "wfa-repos" could not be activated because it does not exist.
[ERROR] Failed to execute goal ro.kuberam.maven.plugins:kuberam-expath-plugin:0.5.4:make-xar (create-xar) on project messaging-replication: Execution create-xar of goal ro.kuberam.maven.plugins:kuberam-expath-plugin:0.5.4:make-xar failed. NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

```

**Comment by claudius108** [comment]
Can you, please, test it with v. 0.5.5?

**Comment by dizzzz** [comment]
Sure!  need to figure out how to integrate this with the archetype....

**Comment by dizzzz** [comment]
no, it is not yet working with v0.5.5:

```
[INFO] --- kuberam-expath-plugin:0.5.5:make-xar (create-xar) @ messaging-replication
.......
[INFO] outputDirectoryPath = C:\Dev\GitHub\messaging-replication\target
[INFO] descriptorsDirectoryPath: C:\Dev\GitHub\messaging-replication\target\expath-descriptors
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource to C:\Dev\GitHub\messaging-replication\target\make-xar-tmp
[INFO] Resolving artifact org.exist:messaging-replication:jar:0.30.4 from null
[INFO] Resolved artifact org.exist:messaging-replication:jar:0.30.4 to C:\Dev\GitHub\messaging-replication\target\messaging-replication-0.30.4.jar fro
m (reactor)
java.io.FileNotFoundException: \\C\Dev\GitHub\messaging-replication\target\messaging-replication-0.30.4.jar (The network path was not found)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:103)
        at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
        at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:94)
        at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
        at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
        at java.net.JarURLConnection.getManifest(JarURLConnection.java:231)
        at java.net.JarURLConnection.getMainAttributes(JarURLConnection.java:283)
        at ro.kuberam.maven.plugins.expath.mojos.MakeXarMojo.getMainClass(MakeXarMojo.java:408)
        at ro.kuberam.maven.plugins.expath.mojos.MakeXarMojo.execute(MakeXarMojo.java:277)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:955)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 50.041 s
[INFO] Finished at: 2018-02-14T12:48:28+01:00
[INFO] Final Memory: 49M/2115M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal ro.kuberam.maven.plugins:kuberam-expath-plugin:0.5.5:make-xar (create-xar) on project messaging-replication: Execution
create-xar of goal ro.kuberam.maven.plugins:kuberam-expath-plugin:0.5.5:make-xar failed.: NullPointerException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
...

**Comment by claudius108** [comment]
Do you have org.exist:messaging-replication:jar:0.30.4 in your local repo?

**Comment by dizzzz** [comment]
Yes, the file is in "C:\Dev\GitHub\messaging-replication\target\messaging-replication-0.30.4.jar" ....

in the trace i see `\\C\Dev\GitHub\messaging-replication\target\messaging-replication-0.30.4.jar` ... s that correct?

**Comment by claudius108** [comment]
Try add org.exist:messaging-replication:jar:0.30.4 as dependencySet.

**Comment by dizzzz** [comment]
this is already there: as generated:

![image](https://user-images.githubusercontent.com/1700062/36203750-eac022b8-1188-11e8-8f81-62baca0df828.png)

isn't that good enough?

**Comment by claudius108** [comment]
Sorry, I have not noticed it.

**Comment by claudius108** [comment]
I will look why this happens.

**Comment by claudius108** [comment]
Can you, please, test it with v. 0.5.6-SNAPSHOT?

**Comment by dizzzz** [comment]
still waiting for feedback of @adamretter ....

**Comment by claudius108** [comment]
Is it him who have to test?

**Comment by dizzzz** [comment]
the problem is.... I do now know how to use `kuberam-expath-plugin` in relation to the `exist-apps-archetype` in "production" , but I have no clue yet how to test things during development/testing.....

**Comment by adamretter** [comment]
@dizzzz So this is just Maven stuff, basically the steps:

1. Clone the Kuberam repo and `mvn clean install` to install the 0.5.6-SNAPSHOT version
2. Clone the exist-apps-archetype and edit the `src/main/resources/archetype-resources/pom.xml` to use the 0.5.6-SNAPSHOT version of kuberam that you just installed, and then `mvn install` to install a snapshot of the `exist-apps-archetype`
3. Run the mvn archetype command with the snapshot version you just installed.

**Comment by dizzzz** [comment]
no it is not functional yet....

```
[INFO] --- kuberam-expath-plugin:0.5.6-SNAPSHOT:make-xar (create-xar) @ wessels ---
[INFO] outputDirectoryPath = C:\XXXXXX\target
[INFO] descriptorsDirectoryPath: C:\XXXXXX\target\expath-descriptors
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource to C:\XXXXXX\target\make-xar-tmp
[INFO] Resolving artifact com.dannes:wessels:jar:1.0-SNAPSHOT from null
[INFO] Resolved artifact com.dannes:wessels:jar:1.0-SNAPSHOT to C:\XXXXXX\target\wessels-1.0-SNAPSHOT.jar from (reactor)
java.io.FileNotFoundException: \\C\XXXXXX\target\wessels-1.0-SNAPSHOT.jar (The network path was not found)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:103)
        at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
        at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:94)
```

**Comment by claudius108** [comment]
Can you test again, pls?

**Comment by dizzzz** [comment]
yes it is working :-) :+1:

**Comment by adamretter** [comment]
@dizzzz @claudius108 so do we expect another release?

**Comment by claudius108** [comment]
Version 0.5.6 is already released.

**Comment by dizzzz** [comment]
thank you @claudius108  for the fast follow-up!
